{% set name = "stemflow" %}
{% set version = "0.0.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 46fa5569a87820b2cb6d4b8e92288159b8ede4a93442e6f5eace0f243deb661a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip

  run:
    - python >=3.8
    - geopandas >=0.11.1
    - h3pandas >=0.2.3
    - matplotlib-base >=3.7.1
    - numpy >=1.24.3
    - pandas >=2.0.3
    - scikit-learn >=1.2.2
    - seaborn >=0.11.2
    - tqdm >=4.65.0
    - xgboost >=1.7.6
    - watermark >=2.3.1
    - scipy>=1.10.1

test:
  imports:
    - stemflow
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/chenyangkang/stemflow
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A package for Adaptive Spatio-Temporal Model (AdaSTEM) in python"
  doc_url: https://chenyangkang.github.io/stemflow/
  dev_url: https://github.com/chenyangkang/stemflow
  description: |
    stemflow is a toolkit for Adaptive Spatio-Temporal Model (AdaSTEM) in python. 
    A typical usage is daily abundance estimation using eBird citizen science data. 
    It leverages the "adjacency" information of surrounding target values in space and time, 
    to predict the classes/continues values of target spatial-temporal point.

extra:
  recipe-maintainers:
    - chenyangkang
