{% set name = "stemflow" %}
{% set version = "1.0.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 597a61b9c16489a562a315b6701d25b9a3ab5964aca096bf82d44517645ee9fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip

  run:
    - python >=3.8
    - matplotlib-base >=3.7.1
    - numpy >=1.24.3
    - pandas >=2.0.3
    - scikit-learn >=1.2.2
    - tqdm >=4.65.0
    - scipy >=1.10.1


test:
  imports:
    - stemflow
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/chenyangkang/stemflow
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A package for Adaptive Spatio-Temporal Model (AdaSTEM) in python"
  doc_url: https://chenyangkang.github.io/stemflow/
  dev_url: https://github.com/chenyangkang/stemflow
  description: |
    stemflow is a toolkit for Adaptive Spatio-Temporal Model (AdaSTEM) in python. 
    A typical usage is daily abundance estimation using eBird citizen science data. 
    It leverages the "adjacency" information of surrounding target values in space and time, 
    to predict the classes/continues values of target spatial-temporal point.

extra:
  recipe-maintainers:
    - chenyangkang
