{% set name = "stemflow" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 799c40a3b5de4775d1321ccc581cca260d232eca073aed7c52d6d709baddfb75

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=65.0.0

  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.7.1
    - numpy >=1.24.3, <2
    - pandas >=2.0.3
    - scikit-learn >=1.2.2
    - tqdm >=4.65.0
    - scipy >=1.10.1
    - plotly >=5.9.0
    - joblib >=1.3.0

test:
  imports:
    - stemflow
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/chenyangkang/stemflow
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A package for Adaptive Spatio-Temporal Model (AdaSTEM) in python"
  doc_url: https://chenyangkang.github.io/stemflow/
  dev_url: https://github.com/chenyangkang/stemflow
  description: |
    stemflow is a toolkit for Adaptive Spatio-Temporal Model (AdaSTEM) in python. 
    A typical usage is daily abundance estimation using eBird citizen science data. 
    It leverages the "adjacency" information of surrounding target values in space and time, 
    to predict the classes/continuous values of target spatial-temporal points.

extra:
  recipe-maintainers:
    - chenyangkang
